ui:
  width: {{ .Env.SCREEN_WIDTH }}
  height: {{ .Env.SCREEN_HEIGHT }}
  customCss:
    - {{ .ConfigPath }}/assets/style.css
modules:
  - name: simple-clock
    uri: https://github.com/glasslabs/clock/releases/download/v1.0.0/clock.wasm
    position: top:right
  - name: simple-weather
    uri: https://github.com/glasslabs/weather/releases/download/v1.0.0/weather.wasm
    position: top:left
    config:
      locationId: 996506
      appId: {{ .Secrets.weather.appId }}
      units: metric
  - name: simple-calendar
    uri: https://github.com/glasslabs/calendar/releases/download/v1.0.0/calendar.wasm
    position: top:right
    config:
      timezone: Africa/Johannesburg
      maxDays: 5
      calendars:
        - url: https://www.calendarlabs.com/ical-calendar/ics/68/South_Africa_Holidays.ics
        - url: {{ .Secrets.calendar.myCalendar }}
  - name: solar
    uri: https://github.com/glasslabs/solar/releases/download/v1.0.2/solar.wasm
    position: bottom:left
    config:
      url: {{ .Secrets.hass.url }}
      token: {{ .Secrets.hass.token }}
      sensorIds:
        load: sensor.deye_sunsynk_sol_ark_load_power
        pv: sensor.deye_sunsynk_sol_ark_pv_power
        battery: sensor.deye_sunsynk_sol_ark_battery_power
        batterySoC: sensor.deye_sunsynk_sol_ark_battery_state_of_charge
        grid: sensor.deye_sunsynk_sol_ark_grid_power
        gridFrequency: sensor.deye_sunsynk_sol_ark_grid_frequency
      battery:
        warning: 50
        low: 30
      maxWatts: 6000
  - name: hass-floorplan
    uri: https://github.com/glasslabs/hass-floorplan/releases/download/v1.0.0/hass-floorplan.wasm
    position: bottom:center
    config:
      url: {{ .Secrets.hass.url }}
      token: {{ .Secrets.hass.token }}
      floorplan: floorplan.svg
