ui:
  width: {{ .Env.SCREEN_WIDTH }}
  height: {{ .Env.SCREEN_HEIGHT }}
  customCSS: {{ .ConfigPath }}/assets/style.css
modules:
  - name: simple-clock
    path: github.com/glasslabs/clock
    version: v0.1.0
    position: top:right
  - name: simple-weather
    path: github.com/glasslabs/weather
    version: v0.1.0
    position: top:left
    config:
      locationId: 996506
      appId: {{ .Secrets.weather.appId }}
      units: metric
  - name: simple-calendar
    path: github.com/glasslabs/calendar
    version: v0.1.0
    position: top:right
    config:
      timezone: Africa/Johannesburg
      maxDays: 5
      calendars:
        - url: https://www.calendarlabs.com/ical-calendar/ics/68/South_Africa_Holidays.ics
        - url: {{ .Secrets.calendar.myCalendar }}
  - name: hass-floorplan
    path: github.com/glasslabs/hass-floorplan
    version: v0.1.0
    position: bottom:center
    config:
      url: {{ .Secrets.hass.url }}
      token: {{ .Secrets.hass.token }}
      floorplan: {{ .ConfigPath }}/assets/floorplan.svg
